spring:
  application:
    name: Learn-SpringAI-Demo

  jackson:
    property-naming-strategy: SNAKE_CASE

  # ── MySQL  Configuration ─────────────────────────────────────────
  datasource:
    url: jdbc:mysql://localhost:3306/techdesk
    username: root
    password: NewPassword123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ── Redis Configuration ─────────────────────────────────────────
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://root:NewPassword123@localhost:27018/knowledge_desk?authSource=admin

  # ── Cache ──────────────────────────────────────────
  cache:
    type: redis
    redis:
      time-to-live: 600000       # 10 minutes in milliseconds


  ai:
    model:
      embedding: openai

    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: RAG_Example_Collection

    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
      embedding:
        options:
          model: text-embedding-3-small

    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

  docker:
    compose:
      stop:
        command: down

logging:
    level:
      org:
        springframework:
          ai:
            chat:
                client:
                  advisor: DEBUG

# ── All prompt file paths defined here ──────────────────────────────────────
app:
  rag:
    pdf-location-pattern: classpath*:/rag/pdfs/*.pdf
    tika-location-patterns: classpath*:/rag/documents/*.pdf,classpath*:/rag/documents/*.docx,classpath*:/rag/documents/*.txt,classpath*:/rag/documents/*.html

  prompts:
    ariaSystemPrompt: classpath:prompts/system/aria-system.st
    maxSystemPrompt: classpath:prompts/system/max-system.st
    seniorAgentSystemPrompt: classpath:prompts/system/senior-agent-system.st
    supportUserPrompt: classpath:prompts/user/support-user.st
    escalationUserPrompt: classpath:prompts/user/escalation-user.st
    stuffedPrompt: classpath:prompts/prompt_stuffing/stuffedPrompt.st

server:
  port: 8081




# Start the container first
#  docker-compose up -d
#
#  Pull LLaMA 3.2 into the container
#  docker exec -it ollama ollama pull llama3.2
#
#  Verify it downloaded
#  docker exec -it ollama ollama list
#
#  Run it
#  docker exec -it ollama ollama run llama3.2

# Test the API

# Should return list of models as JSON
# curl http://localhost:11434/api/tags

# Quick test prompt

# curl -X POST http://localhost:11434/api/generate \
#      -H "Content-Type: application/json" \
#      -d '{
#            "model": "llama3.2",
#            "messages": [
#              {"role": "system", "content": "You are a helpful assistant."},
#              {"role": "user", "content": "What is the capital of France?"}
#            ],
#            "max_tokens": 50
#          }'
